update

diff --git a/.github/workflows/app.ci.yml b/.github/workflows/app.ci.yml
--- a/.github/workflows/app.ci.yml
+++ b/.github/workflows/app.ci.yml
@@ -43,41 +43,7 @@ jobs:
       if: ${{ failure() }}
       run: rm -rf ./screenshots
 
-  # pointclub:
-  #   runs-on: macos-11
-  #   steps:
-  #   - uses: actions/checkout@v3
-  #   - uses: actions/setup-node@v3
-  #     with:
-  #       node-version: 16
-  #       cache: 'yarn'
-  #   - name: Install Appium
-  #     uses: FinbertMDS/setup-appium@latest
-  #     with:
-  #       appium-version: "1.20.2"
-  #   - name: Install dependencies
-  #     run: yarn install --frozen-lockfile
-  #   - name: Run Appium Tests
-  #     uses: reactivecircus/android-emulator-runner@v2
-  #     env:
-  #       RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
-  #       RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
-  #     with:
-  #       api-level: 28
-  #       target: google_apis
-  #       emulator-build: 7425822
-  #       script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:pointclub)"
-  #   - name: upload-artifact
-  #     if: ${{ failure() }}
-  #     uses: actions/upload-artifact@v2
-  #     with:
-  #       name: upload-screenshots
-  #       path: screenshots
-  #   - name: remove-screenshots
-  #     if: ${{ failure() }}
-  #     run: rm -rf ./screenshots
-
-  recipe:
+  pointclub:
     runs-on: macos-11
     steps:
     - uses: actions/checkout@v3
@@ -100,7 +66,7 @@ jobs:
         api-level: 28
         target: google_apis
         emulator-build: 7425822
-        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:recipe)"
+        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:pointclub)"
     - name: upload-artifact
       if: ${{ failure() }}
       uses: actions/upload-artifact@v2
@@ -110,6 +76,40 @@ jobs:
     - name: remove-screenshots
       if: ${{ failure() }}
       run: rm -rf ./screenshots
+
+  # recipe:
+  #   runs-on: macos-11
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #   - uses: actions/setup-node@v3
+  #     with:
+  #       node-version: 16
+  #       cache: 'yarn'
+  #   - name: Install Appium
+  #     uses: FinbertMDS/setup-appium@latest
+  #     with:
+  #       appium-version: "1.20.2"
+  #   - name: Install dependencies
+  #     run: yarn install --frozen-lockfile
+  #   - name: Run Appium Tests
+  #     uses: reactivecircus/android-emulator-runner@v2
+  #     env:
+  #       RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
+  #       RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
+  #     with:
+  #       api-level: 28
+  #       target: google_apis
+  #       emulator-build: 7425822
+  #       script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:recipe)"
+  #   - name: upload-artifact
+  #     if: ${{ failure() }}
+  #     uses: actions/upload-artifact@v2
+  #     with:
+  #       name: upload-screenshots
+  #       path: screenshots
+  #   - name: remove-screenshots
+  #     if: ${{ failure() }}
+  #     run: rm -rf ./screenshots
 
   superpointscreen:
     runs-on: macos-11
@@ -145,41 +145,7 @@ jobs:
       if: ${{ failure() }}
       run: rm -rf ./screenshots
 
-  # toshiru:
-  #   runs-on: macos-11
-  #   steps:
-  #   - uses: actions/checkout@v3
-  #   - uses: actions/setup-node@v3
-  #     with:
-  #       node-version: 16
-  #       cache: 'yarn'
-  #   - name: Install Appium
-  #     uses: FinbertMDS/setup-appium@latest
-  #     with:
-  #       appium-version: "1.20.2"
-  #   - name: Install dependencies
-  #     run: yarn install --frozen-lockfile
-  #   - name: Run Appium Tests
-  #     uses: reactivecircus/android-emulator-runner@v2
-  #     env:
-  #       RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
-  #       RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
-  #     with:
-  #       api-level: 28
-  #       target: google_apis
-  #       emulator-build: 7425822
-  #       script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:toshiru)"
-  #   - name: upload-artifact
-  #     if: ${{ failure() }}
-  #     uses: actions/upload-artifact@v2
-  #     with:
-  #       name: upload-screenshots
-  #       path: screenshots
-  #   - name: remove-screenshots
-  #     if: ${{ failure() }}
-  #     run: rm -rf ./screenshots
-
-  pointclub_toshiru:
+  toshiru:
     runs-on: macos-11
     steps:
     - uses: actions/checkout@v3
@@ -202,7 +168,7 @@ jobs:
         api-level: 28
         target: google_apis
         emulator-build: 7425822
-        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:pointclub_toshiru)"
+        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:toshiru)"
     - name: upload-artifact
       if: ${{ failure() }}
       uses: actions/upload-artifact@v2
@@ -212,3 +178,37 @@ jobs:
     - name: remove-screenshots
       if: ${{ failure() }}
       run: rm -rf ./screenshots
+
+  # pointclub_toshiru:
+  #   runs-on: macos-11
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #   - uses: actions/setup-node@v3
+  #     with:
+  #       node-version: 16
+  #       cache: 'yarn'
+  #   - name: Install Appium
+  #     uses: FinbertMDS/setup-appium@latest
+  #     with:
+  #       appium-version: "1.20.2"
+  #   - name: Install dependencies
+  #     run: yarn install --frozen-lockfile
+  #   - name: Run Appium Tests
+  #     uses: reactivecircus/android-emulator-runner@v2
+  #     env:
+  #       RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
+  #       RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
+  #     with:
+  #       api-level: 28
+  #       target: google_apis
+  #       emulator-build: 7425822
+  #       script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:pointclub_toshiru)"
+  #   - name: upload-artifact
+  #     if: ${{ failure() }}
+  #     uses: actions/upload-artifact@v2
+  #     with:
+  #       name: upload-screenshots
+  #       path: screenshots
+  #   - name: remove-screenshots
+  #     if: ${{ failure() }}
+  #     run: rm -rf ./screenshots
